### PR TITLE
fixed responsiveness of cards in dashboard #110

### LINKED ISSUE #110: [BUG] Responsiveness of cards looks of summary cards looks terrible in mobile screen
### Verify this issue hasn't been reported before

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### What

The cards in the dashboard are less responsive and get clamped over one another across different screen sizes ( majorly on mobile devices) 

### Steps to Reproduce

we can use inspect element to detech the issue across different screen sizes

### Screenshots

image

### Do you want to work on this issue?

Yes

### PR DESCRIPTION
**Pull request by Shailendra1703**
# Pull Request Template

## What
closes #110 

### Before 
image

### After
image

## How
simply by adding responsive classes 

## Additional Notes
Add any additional information that might be useful for the reviewers or any related issues that are addressed.

### CODE REVIEW

**Comment by Shailendra1703** [comment]
@manuelalferez  please review and let me know if any changes are required

**Review by manuelalferez — COMMENTED** [review]
Awesome! It looks much better now. Could you please this small issues: 
image

**Comment by Shailendra1703** [comment]
> Awesome! It looks much better now. Could you please this small issues: image


What's the screen resolution of this, is it in tablet mode?

**Comment by manuelalferez** [comment]
If you play with the responsive of the page, you will see that there are moments where the page breaks and looks like this

**Comment by Shailendra1703** [comment]
> If you play with the responsive of the page, you will see that there are moments where the page breaks and looks like this

Yes I have checked it it breaks on tablet mode, will fix it

**Pull request closed without merging**
