### PR TITLE
Made Transaction Page Responsive

### LINKED ISSUE #55: [BUG] Transactions add page not responsive in smaller screens
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The current implementation of the Transactions Add page does not display properly on smaller screens (e.g., mobile devices). Elements are not arranged to fit within the viewport, resulting in a poor user experience.

Expected Behavior:
The Transactions Add page should be fully responsive, ensuring that all input fields, buttons, and information are easily accessible and visually appealing on smaller screens.

Environment:

Browser: (e.g., Chrome, Firefox)
Device: (e.g., iPhone, Android phone)
Screen Size: (e.g., 320px width)

### Steps to Reproduce

Include any relevant details like:

- Go to Transactions tab 
-  Click on +Add section
-  You will see that the add page in mobile screen is not responsive.

### Screenshots

image

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Reason for not responsive : Either padding or margin not set correctly
Proposed Solution: I'll change the padding to make it responsive and If needed, I can also make the table to look like stack in smaller screens so that it would be neat.

### PR DESCRIPTION
**Pull request by revanthnetha**
Fixes #55 
Changed the padding of the content to make it responsive in smaller screens.
image

Note : while installing locally, the project requires supabase-js. So included supabase-js in dependencies.

### CODE REVIEW

**Comment by manuelalferez** [comment]
@revanthnetha @revanthnetha, I’m still seeing some bugs. There is horizontal scrolling, which doesn’t make sense because it creates confusion. All fields should be visible:

image

Also, I don't see it being responsive. I suggest visualizing the content vertically on mobile screens so the fields would look arranged in two columns. 

image

Something like this, for smaller screens: 
image

**Comment by revanthnetha** [comment]
image

- [ ] Fixed horizontal scrolling issue
- [ ]  Implemented responsive design for mobile screens
- [ ]  Arranged fields in two columns on smaller screens

**Comment by manuelalferez** [comment]
@revanthnetha amazing work!

**Comment by manuelalferez** [comment]
It seems that there hasn't been a response yet. Great job arranging the fields in rows! I think that approach has been well integrated

As a suggestion, to enhance usability, consider avoiding horizontal scrolling. If the screen size doesn't accommodate all the fields side by side, it might be better to rearrange them vertically.
https://github.com/user-attachments/assets/1454835e-ed23-4cbe-83de-eab6a7281265

This should be aligned; it doesn't look good when it’s misaligned:
image

**Comment by revanthnetha** [comment]
Got it @manuelalferez.I'll make the changes as expected.

**Comment by revanthnetha** [comment]
image

Screenshot 2024-10-09 234334


Approach : 
1. Fixed the Scrolling issue in lg screens by setting w-auto in page.tsx
2. Made Responsive in smaller screens by adjusting margins and flex-box.

If anything needs to be changed. Happy to discuss :) @manuelalferez

**Comment by manuelalferez** [comment]
@revanthnetha amazing job!! You took your time with this one, thanks for approaching all the issues along the way. It's great to work with people like you. Super profesional 👏

**Pull request merged**
